In [1]:
import asimov_database as ad

In [2]:
monitora =  ad.Monitoring()

In [6]:
#Retorna total de arquivos por subdiretório  (/bigdata)
monitora.total_count()

/bigdata 13657 Files
/bigdata/order-book 360 Files
/bigdata/logs 94 Files
/bigdata/trades-manual 1 Files
/bigdata/mirror 42 Files
/bigdata/mirror/backup 6 Files
/bigdata/trades 1498 Files
/bigdata/level-book 286 Files
/bigdata/.Trash-1000 982 Files
/bigdata/.Trash-1000/expunged 0 Files
/bigdata/events 10333 Files
/bigdata/confirmations 57 Files
/bigdata/realtime-book 0 Files
/bigdata/database 4 Files

In [3]:
#Retorna tamanho em (gb) de cada subdiretório (/bigdata)

monitora.total_size()

/bigdata 604.470540985 GygaBytes
/bigdata/order-book 580.275301297 GygaBytes
/bigdata/trades 1.626934565 GygaBytes
/bigdata/level-book 3.950947285 GygaBytes
/bigdata/events 18.014314618 GygaBytes

In [4]:
# #Retorna qntdade de arquivos criados por dia

monitora.files_per_day()

            File
Date
2019-08-06    10
2019-10-11  3475
2019-10-12   334
2019-10-13  1634
2019-10-24     6
2019-11-18    79
2019-11-21     3
2019-11-30    84
2019-12-05   547
2019-12-07    12
2019-12-09  1704
2019-12-10   823
2019-12-11    91
2019-12-12    94
2019-12-13    95
2019-12-16    91
2019-12-17    88
2019-12-20   273
2019-12-23     6
2020-01-06   818
2020-01-07    87
2020-01-08    90
2020-01-09   102
2020-01-10   115
2020-01-13   112
2020-01-14    90
2020-01-15    80
2020-01-16   128
2020-01-17   146
2020-01-18   150
2020-01-20    37
2020-01-21   233
2020-01-22    96
2020-01-23    90
2020-01-24    89
2020-01-25    36
2020-01-27     3
2020-01-28   108
2020-01-29   303
2020-01-30   137
2020-01-31     2
2020-02-03   219
2020-02-04   157
2020-02-05   213